/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.io.File;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import model.Usuario;
import utils.Util;
import java.util.List;
import javax.swing.Icon;

/**
 *
 * @author Administrador
 */
public class FrAltUsuario extends javax.swing.JDialog {

    private int pkUsuario;

    /**
     * Creates new form FrAltUsuario
     */
    public FrAltUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void setPkUsuario(int pkUsuario) {
        this.pkUsuario = pkUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        editUsuarioAlt = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        editConfirmSenhaAlt = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        lblBemVindo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlFoto = new javax.swing.JPanel();
        imgFoto = new javax.swing.JLabel();
        btnEscolherImagem = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        lblUsuario1 = new javax.swing.JLabel();
        editEmailAlt = new javax.swing.JTextField();
        chkAtivo = new javax.swing.JCheckBox();
        txtDataNascimentoAlt = new javax.swing.JFormattedTextField();
        lblData = new javax.swing.JLabel();
        lblSenha1 = new javax.swing.JLabel();
        editSenhaAlt = new javax.swing.JPasswordField();
        editCodigoAlt = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        btnAlterarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AlterarUsuario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblLogin.setText("Alterar Usuario");

        editUsuarioAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsuarioAltActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsuario.setText("Usuário");

        jPanel3.setBackground(new java.awt.Color(25, 219, 193));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBemVindo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblBemVindo.setForeground(new java.awt.Color(255, 255, 255));
        lblBemVindo.setText("Bem Vindo !");
        jPanel3.add(lblBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(25, 219, 193));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, 40));

        pnlFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFotoLayout = new javax.swing.GroupLayout(pnlFoto);
        pnlFoto.setLayout(pnlFotoLayout);
        pnlFotoLayout.setHorizontalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        pnlFotoLayout.setVerticalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        jPanel3.add(pnlFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 280, 240));

        btnEscolherImagem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEscolherImagem.setText("Escolher Imagem");
        btnEscolherImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEscolherImagemMouseClicked(evt);
            }
        });
        btnEscolherImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherImagemActionPerformed(evt);
            }
        });
        jPanel3.add(btnEscolherImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 170, 40));

        lblSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSenha.setText("Senha");

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        btnSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarKeyPressed(evt);
            }
        });

        lblUsuario1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUsuario1.setText("E-mail");

        editEmailAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmailAltActionPerformed(evt);
            }
        });

        chkAtivo.setText("Ativo");

        txtDataNascimentoAlt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txtDataNascimentoAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoAltActionPerformed(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblData.setText("Data");

        lblSenha1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSenha1.setText("Confirmar Senha");

        editSenhaAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSenhaAltActionPerformed(evt);
            }
        });

        editCodigoAlt.setEditable(false);

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCodigo.setText("Codigo");

        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarSenhaMouseClicked(evt);
            }
        });
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigo)
                                    .addComponent(editCodigoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(lblLogin))
                            .addComponent(lblData)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDataNascimentoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(chkAtivo))
                            .addComponent(editEmailAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editConfirmSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha1)
                            .addComponent(editSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha)
                            .addComponent(lblUsuario1)
                            .addComponent(editUsuarioAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCodigoAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editUsuarioAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editEmailAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editConfirmSenhaAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblData)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAtivo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDataNascimentoAlt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editUsuarioAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsuarioAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUsuarioAltActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        gravar();
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarKeyPressed

    }//GEN-LAST:event_btnSalvarKeyPressed

    private void editEmailAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmailAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmailAltActionPerformed

    private void txtDataNascimentoAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoAltActionPerformed

    private void editSenhaAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSenhaAltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSenhaAltActionPerformed

    private void btnAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarSenhaMouseClicked
        if (editSenhaAlt.isEditable()) {
            editSenhaAlt.setEditable(false);
            editConfirmSenhaAlt.setEditable(false);
            editSenhaAlt.setBackground(java.awt.Color.GRAY);
            editConfirmSenhaAlt.setBackground(java.awt.Color.GRAY);

            editSenhaAlt.setText("");
            editConfirmSenhaAlt.setText("");

            btnAlterarSenha.setText("Alterar Senha");

        } else {
            editSenhaAlt.setEditable(true);
            editConfirmSenhaAlt.setEditable(true);

            btnAlterarSenha.setText("Cancelar Alterar Senha");

        }
    }//GEN-LAST:event_btnAlterarSenhaMouseClicked


    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        this.setIconImage(Util.getIcone());

        //carrega os dados do usuario
        UsuarioController controller = new UsuarioController();

        //consulta os usuario com o codigo igual
        List<Usuario> lista = controller.consultar(0, String.valueOf(pkUsuario));

        Usuario usu = null;
        usu = lista.get(0);

        //preencher os campos com a variavel usu
        editCodigoAlt.setText(String.valueOf(usu.getPkUsuario()));
        editUsuarioAlt.setText(usu.getNome());
        editEmailAlt.setText(usu.getEmail());

        txtDataNascimentoAlt.setText(
                Util.converterDateToString(usu.getDataNascimento()));

        chkAtivo.setSelected(usu.isAtivo());
        imgFoto.setIcon(usu.getImagem());

    }//GEN-LAST:event_formWindowOpened

    private void btnEscolherImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscolherImagemMouseClicked
        //escolher img
        File arquivo = Util.escolherImagem();

        //carregar img
        if(arquivo != null) {
            //converte
            Icon icone = Util.converterFileToIcon(arquivo);

            //redimencionar
            Icon iconeNovo = Util.redimensionarImagem(icone, 278, 238);

            imgFoto.setIcon(iconeNovo);
        }

    }//GEN-LAST:event_btnEscolherImagemMouseClicked

    private void btnEscolherImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscolherImagemActionPerformed

    private void gravar() {
        //validar os campos preenchidos
        if (!verificarCampos()) {
            return;
        }

        //ler os campos e guardar objeto
        Usuario usu = new Usuario();
        usu.setPkUsuario(Integer.parseInt(editCodigoAlt.getText()));
        usu.setNome(editUsuarioAlt.getText());
        usu.setEmail(editEmailAlt.getText());
        if(editSenhaAlt.isEditable()){
        usu.setSenha(Util.calcularHash(new String(editSenhaAlt.getPassword())));
        }
        usu.setDataNascimento(Util.converterStringToDate(txtDataNascimentoAlt.getText()));
        usu.setAtivo(chkAtivo.isSelected());
        usu.setImagem(imgFoto.getIcon());

        //enviar para o banco de dados
        UsuarioController controller = new UsuarioController();
        if (controller.alterar(usu)) {
            JOptionPane.showMessageDialog(null, "foi");
            this.dispose();
        }

    }

    private boolean verificarCampos() {

        if (editUsuarioAlt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'Usuario' em branco");
            return false;
        }
        if(editSenhaAlt.isEditable()){
        if (new String(editConfirmSenhaAlt.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'senha' em branco");
            return false;
        }
       }
        if (editEmailAlt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo 'email' em branco");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltUsuario dialog = new FrAltUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnEscolherImagem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JTextField editCodigoAlt;
    private javax.swing.JPasswordField editConfirmSenhaAlt;
    private javax.swing.JTextField editEmailAlt;
    private javax.swing.JPasswordField editSenhaAlt;
    private javax.swing.JTextField editUsuarioAlt;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPanel pnlFoto;
    private javax.swing.JFormattedTextField txtDataNascimentoAlt;
    // End of variables declaration//GEN-END:variables
}
